# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b987d3dae138aea23594a4932b91222425795f40c1fa8651d8574706d73c9f10fcf1bd3210e873c504a7d5533d9979908e57fcc7547ed73c4534d5b0e42f66e8

test:
  secret_key_base: 8c8890c90b90a4cfa7d4d1d96b4942c16bf32f99465ffef8c34806c7afe7e28c44ac648a9b5d229674e7bba9a29647c50572bdd532efbc17fb8c1dce487269ff

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
